import crypto from 'node:crypto';
import {config} from '../../../core/config/index.js';
import {prisma} from '../../../core/database/prisma.js';
import {AppError} from '../../../shared/errors/app-error.js';
import {decryptToken,encryptToken} from './xero.crypto.js';
import {discoverTenants,createXeroClient} from './xero.client.js';
import {exchangeCode} from './xero.oauth.js';

const refreshLocks=new Map();
const audit=(client,actorUserId,action,entityId=null,metadata=null)=>client.auditLog.create({data:{actorUserId,action,entityType:'XeroConnection',entityId,metadata}});
export async function status({client=prisma}={}){const connection=await client.xeroConnection.findFirst({where:{isActive:true},select:{id:true,tenantName:true,lastSuccessfulSyncAt:true,lastAttemptedSyncAt:true,lastSyncStatus:true,lastSyncErrorCode:true,token:{select:{accessTokenExpiresAt:true,refreshTokenUpdatedAt:true}}}});return {configured:config.xero.enabled,connected:Boolean(connection),tenantName:connection?.tenantName||null,lastSuccessfulSyncAt:connection?.lastSuccessfulSyncAt||null,lastAttemptedSyncAt:connection?.lastAttemptedSyncAt||null,lastSyncStatus:connection?.lastSyncStatus||null,lastSyncErrorCode:connection?.lastSyncErrorCode||null,tokenHealth:!connection?'UNAVAILABLE':connection.token.accessTokenExpiresAt>Date.now()?'HEALTHY':'REFRESH_REQUIRED',availableActions:{connect:config.xero.enabled&&!connection,sync:Boolean(connection),disconnect:Boolean(connection)}};}
export async function completeOAuth(code,actorUserId,{client=prisma,exchange=exchangeCode,discover=discoverTenants}={}){const token=await exchange(code);const tenants=await discover(token.access_token);if(!tenants.length)throw new AppError('No Xero organisations are available for this connection.',400);const expiresAt=new Date(Date.now()+token.expires_in*1000);const pendingId=crypto.randomUUID();const encrypted={access:encryptToken(token.access_token,config.xero.tokenEncryptionKey),refresh:encryptToken(token.refresh_token,config.xero.tokenEncryptionKey)};await client.setting.upsert({where:{key:`xero.pending.${pendingId}`},update:{value:{tenants,encrypted,expiresAt}},create:{key:`xero.pending.${pendingId}`,value:{tenants,encrypted,expiresAt},description:'Short-lived pending Xero tenant selection'}});await audit(client,actorUserId,'XERO_CONNECTION_COMPLETED',null,{tenantCount:tenants.length});return {pendingId,tenants:tenants.map(({tenantId,tenantName,tenantType})=>({tenantId,tenantName,tenantType})),requiresSelection:tenants.length>1};}
export async function selectTenant(pendingId,tenantId,actorUserId,{client=prisma}={}){const pending=await client.setting.findUnique({where:{key:`xero.pending.${pendingId}`}});const tenant=pending?.value?.tenants?.find(item=>item.tenantId===tenantId);if(!tenant)throw new AppError('The selected Xero organisation is not authorised.',400);await client.$transaction(async tx=>{await tx.xeroConnection.updateMany({where:{isActive:true},data:{isActive:false}});const connection=await tx.xeroConnection.upsert({where:{tenantId},update:{tenantName:tenant.tenantName,tenantType:tenant.tenantType,externalConnectionId:tenant.connectionId,isActive:true,disconnectedAt:null},create:{tenantId,tenantName:tenant.tenantName,tenantType:tenant.tenantType,externalConnectionId:tenant.connectionId,isActive:true}});await tx.xeroOAuthToken.upsert({where:{connectionId:connection.id},update:{encryptedAccessToken:pending.value.encrypted.access,encryptedRefreshToken:pending.value.encrypted.refresh,accessTokenExpiresAt:new Date(pending.value.expiresAt),refreshTokenUpdatedAt:new Date(),tokenVersion:{increment:1}},create:{connectionId:connection.id,encryptedAccessToken:pending.value.encrypted.access,encryptedRefreshToken:pending.value.encrypted.refresh,accessTokenExpiresAt:new Date(pending.value.expiresAt),refreshTokenUpdatedAt:new Date()}});await tx.setting.delete({where:{id:pending.id}});await audit(tx,actorUserId,'XERO_TENANT_SELECTED',connection.id,{tenantId});});return {connected:true,tenantName:tenant.tenantName};}
export async function disconnect(actorUserId,{client=prisma}={}){const connection=await client.xeroConnection.findFirst({where:{isActive:true}});if(!connection)throw new AppError('Xero is not connected.',409);await client.$transaction(async tx=>{await tx.xeroOAuthToken.deleteMany({where:{connectionId:connection.id}});await tx.xeroConnection.update({where:{id:connection.id},data:{isActive:false,disconnectedAt:new Date()}});await audit(tx,actorUserId,'XERO_DISCONNECTED',connection.id);});return {disconnected:true};}
export async function authorisedClient({client=prisma,fetchImpl=fetch}={}){const connection=await client.xeroConnection.findFirst({where:{isActive:true},include:{token:true}});if(!connection?.token)throw new AppError('Xero is not connected.',409);if(connection.token.accessTokenExpiresAt>Date.now()+60000)return {connection,xero:createXeroClient({accessToken:decryptToken(connection.token.encryptedAccessToken,config.xero.tokenEncryptionKey),tenantId:connection.tenantId,fetchImpl})};if(refreshLocks.has(connection.id))return refreshLocks.get(connection.id);const work=(async()=>{const refresh=decryptToken(connection.token.encryptedRefreshToken,config.xero.tokenEncryptionKey);const response=await fetchImpl(config.xero.tokenUrl,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${config.xero.clientId}:${config.xero.clientSecret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:refresh})});if(!response.ok)throw new AppError('Xero token refresh failed.',502);const token=await response.json();if(!token.access_token||!token.refresh_token)throw new AppError('Xero token refresh failed.',502);await client.xeroOAuthToken.update({where:{connectionId:connection.id},data:{encryptedAccessToken:encryptToken(token.access_token,config.xero.tokenEncryptionKey),encryptedRefreshToken:encryptToken(token.refresh_token,config.xero.tokenEncryptionKey),accessTokenExpiresAt:new Date(Date.now()+token.expires_in*1000),refreshTokenUpdatedAt:new Date(),tokenVersion:{increment:1}}});return {connection,xero:createXeroClient({accessToken:token.access_token,tenantId:connection.tenantId,fetchImpl})};})();refreshLocks.set(connection.id,work);try{return await work;}finally{refreshLocks.delete(connection.id);}}
